input {
  udp {
    #host => "10.1.1.200"
    port => "10514"
    codec => "json"
    type => "rsyslog"
  }
}

# This is an empty filter block.  You can later add other filters here to further process
# your log lines

filter { }

# This output block will send all events of type "rsyslog" to Elasticsearch at the configured
# host and port into daily indices of the pattern, "rsyslog-YYYY.MM.DD"

output {
  if [type] == "rsyslog" {
    elasticsearch {
	hosts => "elasticsearch:9200"
	user => "logstash_internal"
	password => "${LOGSTASH_INTERNAL_PASSWORD}"
    }
  }
}

